seed: 0
cutoff_date: "2021-06-01"
test_cutoff_date: "2022-05-01"
max_len: 384
batch_size: 1
learning_rate: 2.0e-4
weight_decay: 0.0
mixed_precision: "bf16"
model_config_path: "../working/configs/pairwise.yaml"  # Adjust path as needed
epochs: 50
cos_epoch: 35
loss_power_scale: 1.0
max_cycles: 1
grad_clip: 1.0
gradient_accumulation_steps: 1
d_clamp: 30
max_len_filter: 9999999
min_len_filter: 10
structural_violation_epoch: 50
balance_weight: false
n_times: 1000
beta_min: 1.0e-4
beta_max: 2.0e-2
decoder_batch_size: 48
decoder_dim: 768
decoder_num_layers: 6
decoder_nhead: 12
pretrained_weight_path: "../../8m_exps/test32/models/epoch_0/pytorch_model_fsdp.bin"
data_std: 35
val_n_steps: 100